---
- name: prepare the servers to use ansible
  become: true
  become_user: modulus
  strategy: free
  gather_facts: no
  hosts: master
  tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
