---
  - name: Add rhel and centos repository
    yum: name=https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el7.noarch.rpm state=present update_cache=yes
    when: ansible_os_family == "RedHat"

  - name: Install salt-minion
    yum: name=salt-minion state=present
    when: ansible_os_family == "RedHat"
