---
  - name: Ensure gpg key is in place
    apt_key:
      url: "https://repo.saltstack.com/apt/ubuntu/{{ansible_distribution_version}}/amd64/latest/SALTSTACK-GPG-KEY.pub"
      state: present

  - name: Ensure saltstack repo for ubuntu is in place
    template: src="saltstack.list.j2" dest="/etc/apt/sources.list.d/saltstack.list" owner="root" mode="0644"

  - name: Install salt-minion package
    apt:
      name: salt-minion
      update_cache: yes


  - name: Setup minion
    template: src="minion.conf.j2" dest="/etc/salt/minion" owner="root" mode="644"

  - name: restart salt-minion service
    service:
      name: salt-minion
      state: restarted
    register: restart_facts

  - name: Debug restart
    debug: msg="{{restart_facts}}"
