---
  - include: ubuntu.yml
  - include: centos.yml

  - name: Setup minion
    template: src="minion.conf.j2" dest="/etc/salt/minion" owner="root" mode="644"
    when: ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat"

  - name: restart salt-minion service
    service:
      name: salt-minion
      state: restarted
    register: restart_facts


  #- name: Debug restart
  #debug: msg="{{restart_facts}}"
