---
  - name: Ensure python-pip is installed
    apt: name=python3-pip state=present

  - name: Ensure IPy is pip installed
    pip: name=ipy state=present

  - name: Ensure requests is pip installed
    pip: name=requests state=present

  - name: Ensure Dulwich is absent
    apt: name=python-dulwich state=absent

  - name: Ensure pygit2 is present
    apt: name=python-pygit2 state=present
