---
  - name: ensure image location  exits
    file:
      path: "{{image_location}}"
      state: directory

  - include_tasks: image.yml
    vars:
      item: "{{image}}"
    with_items: "{{images}}"
    loop_control:
      loop_var: image
