---
  - name: ensure lcx image location exist
    file:
      path: "{{lxc_image_location}}"
      state: directory

  - include_tasks: image.yml
    vars:
      item: "{{image}}"
    with_items: "{{lxc_images}}"
    loop_control:
      loop_var: image
